#!/usr/bin/env python3
"""
apply_patch.py

The Deterministic Actuator.
Reads a raw LLM response from stdin, extracts the SEARCH/REPLACE blocks,
and performs a deterministic string replacement patch on the target file.

Usage: cat ai_response.md | python scripts/apply_patch.py
"""

import sys
import re
import os
import subprocess

# ONE TIMELINE, NO PREVIEWS: every command in the response appears exactly once, in the section where it executes, in execution order -- PROBES (read-only) first, then PATCHES as numbered cars with any dependent actuator or ignition as the LAST cars, then PROMPT. A command that depends on a patch is never quoted above that patch, not as a preview, not "for later"; if it must be mentioned early, name it ("Car 3, the smoke") and show nothing.
# THE HUMAN IS NOT THE BRANCH PREDICATE (banked 2026-09-24, after the Chrome
# profile census ride made the operator decide whether Car 1's output licensed
# Car 2, then whether Car 2 licensed Car 3). A patch train is compiled control
# flow. The human actuates cars; the human does not evaluate branches between
# them. If patch B is justified only by evidence that patch A will create, B
# DOES NOT RIDE THIS TURN. End the turn after A, collect its AFTER receipt in
# the next compile, and decide about B there. Multiple patch cars may share one
# turn only when every car is already justified by evidence present when the
# answer is written. Never say "if this prints X, apply the next patch." That is
# an uncompiled conditional handed to a tired person.
#
# ONE OPERATOR INTERFACE (banked 2026-09-24, same conviction). For this
# operator, each patch car already has four controls: patch, app, d, m. Emit the
# SEARCH/DIVIDER/REPLACE payload and let those controls actuate, inspect, and
# commit it. DO NOT also emit expanded duplicates such as `cat patch | python
# apply.py`, `git diff`, `git add`, or `git commit`. An ALREADY APPLIED receipt
# caused by the model telling the human to actuate the same car twice is not a
# safety check; it is duplicate work generated by the model.
#
# PUSH IS ASSUMED (banked 2026-09-24, operator's standing rule). Immediately
# after the final m in a patch series the operator runs git push to put the
# newest commits offsite. Do not emit blast. Do not emit git push. Do not make
# pushing conditional on another reading. The operator owns that invariant and
# performs it automatically; repeating it spends attention without adding
# information.
#
# IGNITION IS A SENTENCE (banked 2026-09-24). When patched code must be run,
# reloaded, restarted, sourced, or otherwise actuated before an AFTER receipt
# can mean anything, close PATCHES with exactly one plain imperative:
# `Ignition: <exact command or action>.` If nothing needs ignition, say
# `Ignition: none.` Never imply ignition by describing expected output, and
# never make the human infer the command from prose.
#
# THE ANSWER IS THE ARTIFACT (banked 2026-09-24, convicted the turn it was
# named). The model offered to render a case card as a host-side "Artifact"
# panel one breath before being told those are forbidden. An Artifact is
# unsigned, unhashed, unversioned, and lives OUTSIDE the cartridge -- the exact
# trusting-trust binary this system exists to abolish, in a convenience's
# clothes. THE RULE: the only durable outputs are the sealed cartridge
# (qamy.zip = prompt.md + payload.md + manifest.json) and the copyable text of
# the response. Never emit, offer, or route work into an Artifact, canvas, or
# side panel. A finding that cannot be pasted here and rebuilt from the manifest
# is not a finding.
#
# NEXT CONTEXT IS PASTE-READY OR IT IS SABOTAGE (banked 2026-09-24, convicted by
# an operator who had to hand-translate a prose paragraph back into adhoc.txt
# lines). Car 2 was written "Add, in this order of value: (1)... (2)..." --
# English, not includes. This system exists to KILL that copy-paste correlation
# work, and a prose NEXT CONTEXT hands it straight back to a tired human in an
# internet cafe. THE RULE: (2) NEXT CONTEXT is ALWAYS a single fenced block of
# literal adhoc.txt lines -- bare paths, `! ` command lines, `!`/`?`/`@` URL
# lines -- paste-ready under the operator's markers with zero editing. Active
# includes are bare; uncertain lines are commented placeholders the operator
# completes. Prose goes OUTSIDE the block. Every probe from (1) reappears here
# with a leading "! " per THE PROBE ECHO INVARIANT.
#
# A PROBE RUNS ON THE OPERATOR'S MACHINE OR IT IS NOT A PROBE (banked
# 2026-09-24, convicted by four dead probes in one car). (1) PROBES pointed at
# /root/.claude/... -- paths that exist only on the model's ephemeral cloud
# disk -- so every jq and grep answered "No such file or directory" on the
# operator's Mac. The one probe that WORKED carried its evidence inline (a
# base64 blob it decoded on the spot). A probe against a file only the model can
# see is a promissory note, not a falsifier. THREE SUB-RULES:
#   (a) USE rg, NEVER grep. The tree is full of .git/ folders; rg honors
#       .gitignore and skips them, grep recurses into every object.
#   (b) A PROBE TARGETS A FILE THE OPERATOR HAS, or carries its evidence inline.
#       Evidence living only on the model's side is DELIVERED into the cartridge
#       as a real file first, then the probe reads that file.
#   (c) A NAME THAT IS NOT A FILE IS NOT A FILE INCLUDE. A remote MCP tool
#       (html_pageworkers_preview, site_crawler_url_detail) is actuated through
#       connectors/mcp.py, never listed as a bare path; prompt_foo.py answers a
#       bare tool name with "FILE NOT FOUND AND WILL BE SKIPPED" and the context
#       arrives silently empty.
#
# SPELL OUT THE TOOL-CALL YOU ARE MAKING OF THE HUMAN (banked 2026-09-22, at
# the operator's instruction, after a Context car that said "same as last
# turn" and taught nothing). The model reading this file is tool-calling a
# PERSON, and a person cannot ask a paragraph a clarifying question. Polite,
# indirect, erudite or compressed wording is ambiguity, and ambiguity gets
# resolved wrong.
# THE RULE: short words, imperative, one action per line. Never point at
# another turn instead of restating the step: no "same as before", no "as
# above", no "the usual". Never make the human guess which file, which
# command, or which of two readings you meant. Write for someone in a hurry
# on a laptop in an internet cafe who will act on the first sentence that
# looks like an instruction. Example: "Run this in a terminal on Pipulate
# Prime when the power returns," never "carried in full so it is not a
# bibliography."
# NEXT CONTEXT IS THE WHOLE LIST (banked 2026-09-20, convicted the same day,
# and banked HERE because this file rides the fixed tail of every ADHOC
# compile while the constitution does not): the payload a model is reading is
# the ONLY raw source it will ever be allowed to patch, and the operator
# comments the 40K-foot block out on turn two. A file that "is already there"
# this compile is gone next compile. Every file a next-turn car will patch is
# named in full in NEXT CONTEXT -- one that rode this compile, one that rides
# every compile, one the operator knows by heart -- because "already there"
# is a claim about the past wearing the future's label. CONVICTION: a
# three-car caboose said init.lua, flake.nix and index.html were already
# there; the next payload carried mother_cat.py and none of them, and two
# cars waited a turn for raw source the list had waved at. The cost is one
# line per file. THE GROOVE THAT HOLDS: the checklist's own NEXT CONTEXT
# clause in prompt_foo.py is the eventual home, read at the highest-attention
# position of every full-frame compile; this comment is the second groove,
# and a § key in foo_files.py the third.

# THE SCREENSHOT IS NOT A LOCATOR (banked 2026-09-11, two exchanges lost).
# Botify's Confluence pages for custom link attributes say "go to the project
# page on django admin" and show the field ONLY as a screenshot. Two admin
# models sit one click apart and both answer to that phrase:
#   /admin/projects/projectsettings/<id>/change/  -- the crawl config. WRONG.
#     Carries a "Links" heading in the RIGHT SIDEBAR that is Django's
#     related-objects nav (one item: a filtered HTML-extracts list). It appears
#     only when the project HAS html extracts, so it comes and goes and reads
#     exactly like a config section that is sometimes empty.
#   /admin/projects/project/<id>/change/         -- RIGHT. Fieldset "Links" in
#     the FORM BODY, between "Google Cloud" and "Pocket Crawler". The field is
#     labeled "Extract Links Attributes" and takes a JSON array of {"name": ...}.
# WHEN THE DOC'S EVIDENCE IS AN IMAGE, the enumeration is the only locator: walk
# every field label in the fieldset and say which ones are NOT it. A model that
# answers from the doc's prose will send the operator to the sidebar decoy, and
# the operator -- who cannot see the doc's screenshot either -- has no way to
# tell a wrong answer from a right one until they have read every textarea twice.

# ADMIN FORMS ARE CREDENTIAL SURFACES (banked 2026-09-11, cartridge
# foo-d5dfdb65-1342.zip). A `?URL` scrape of a vendor's Django admin renders a
# live secret as a BARE VALUE under its human-readable field label -- no
# assignment, no JSON key, no vendor prefix -- which is the one shape every
# pattern in SECRET_TRIPWIRES was structurally blind to. The gate printed
# "ARMED / 0 hits" and the 0 was ARITHMETICALLY CORRECT for its pattern set,
# so an armed scanner and a blind one wrote the identical line: THE
# DISCRIMINATION QUESTION failing inside the guard itself. Two label-anchored
# patterns landed as a backstop (commit 12e04711) and each covers exactly ONE
# field on ONE vendor's admin; the class is uncovered and generic entropy
# detection is refused on purpose, being the false-positive engine that
# emptied that list once already.
# THE FIX IS THE ROUTING, NOT THE REGEX: send the NARROWEST admin page that
# answers the question. Here, /admin/projects/project/<id>/ carried the field
# the ride needed and no credentials, while /admin/projects/projectsettings/
# <id>/ carried a basic-auth blob and a crawler token in a form nobody had
# read. The scrape that seals a secret cannot be unsealed; the credential is
# rotated instead, by whoever owns it, and that conversation is owed the
# moment it is noticed.

# THE COLD-START EXIT IS A FALSE GREEN (convicted 2026-09-16, by a probe
# written that same turn expressly to be content-free). `wallet.py check
# jira` was echoed as `>/dev/null 2>&1; echo jira_check_exit=$?` on the
# theory that exit 0 means the service accepted the credential just now. It
# printed 0 on a machine with NO WALLET AT ALL. main() evaluates
# load_wallet() BEFORE board(), and load_wallet's ABSENT-IS-NOT-BROKEN
# branch prints the cold-start card and sys.exit(0)s -- so board() never
# ran, no credential was checked, and the receipt read exactly like a green
# board. GOLD IS THE ONLY EXIT-0 CONDITION is a true claim about board(),
# and it was read as a claim about the program.
# TWO RULES, AND THE SECOND IS THE GENERAL ONE:
#   1. AN EXIT CODE IS A VERDICT ONLY FOR THE PATH THAT REACHES IT. Before
#      echoing `cmd >/dev/null; echo $?` as a probe, name every earlier
#      sys.exit(0) on that path. Prefer the narrowest program that owns the
#      question: jira.py --check has no cold-start branch and wallet.py has
#      one, so the connector is the honest instrument and the board is not.
#   2. THE REDIRECT ATE THE DISCRIMINATOR. The cold-start card says in plain
#      words that there is no wallet, on stdout, and the probe threw it away
#      to keep a client host out of the payload. A probe that suppresses
#      output to stay safe must first prove the exit code ALONE still
#      answers the question; otherwise it has traded content for silence and
#      kept neither. Two sibling misses the same day: a probe reading
#      connectors/wallet.json, a path that has never existed, and a
#      `jira | grep -c` whose 2>/dev/null made a dead credential and an
#      empty ticket list print the same 0.
# THE HELP TEXT IS NOT A CENSUS (convicted 2026-09-17, both halves of one
# straddle). Two census probes were written as `rg -o -h PATTERN ... | sort
# | uniq -c` on the belief that -h means --no-filename. In ripgrep -h is
# --help and the no-filename switch is -I, so both probes printed ripgrep's
# own usage screen, hand-run and echoed alike, and uniq -c counted it
# faithfully: a leading "12" (the help screen's blank lines) over a long
# tail of 1s, which is precisely the SHAPE a census of include names would
# have. BEFORE and AFTER agreed perfectly because neither had searched a
# single file. THE RULE: a receipt carrying the instrument's own usage text
# ("Use -h for short descriptions", a flag table, a project home page) is
# a probe that exited before it measured, and every number on it is a
# count of the help screen. Match the shape of the answer to the shape of
# the question before reading a number off it, and spell switches long
# (--no-filename, --only-matching) wherever a single letter has ever meant
# help in some other tool.
# THE PIPELINE ATE THE FALLBACK (convicted 2026-09-21, by a probe that could
# not fail). `ls DIR 2>/dev/null | head -5 || echo no_dir` was echoed to report
# a missing directory. It never could: `||` binds to the whole PIPELINE, and a
# pipeline's exit status is its LAST command's, so head's 0 masks ls's 2 and
# the fallback is UNREACHABLE CODE. The probe printed nothing in the world
# where the directory was missing, and the reader saw a marker sitting right
# there in the source and assumed it would have fired. Third sibling of AN EXIT
# CODE IS A VERDICT ONLY FOR THE PATH THAT REACHES IT: there the dead branch
# was inside a program, here it is inside the shell.
# THE RULE: `||` after a pipe tests the PIPE, never the thing you care about.
# Put the question in a test that owns its own exit -- `test -d DIR && ls DIR |
# head -5 || echo no_dir` -- or make the program itself always print a verdict.
# AND THE GENERAL FORM: a probe whose fallback marker has never been SEEN to
# print has an UNTESTED negative branch. Before echoing one, name the world in
# which it fires and check that the exit status actually reaches it.
#
# THE WRAPPER IS NOT THE MEASUREMENT (convicted 2026-09-22, by a receipt that
# disagreed with itself and was right twice). `time` on a census run read
# real 8m3.689s, while the program's OWN stopwatch, added the same turn, read
# "export POST returned in 123.6s". Both numbers are true. The six minutes
# between them were undetected-chromedriver launching a headful Chrome over
# cafe wifi to harvest one session cookie. Reading the shell's `real` as the
# cost of the export would have overstated it FOURFOLD and sent the next turn
# optimizing the wrong half of the program.
# THE RULE: `time <program>` measures the PROGRAM, never the step inside it
# that the question is about. When a command has an expensive setup phase --
# a browser launch, an auth handshake, an index build, a model load -- the
# step under test carries its own stopwatch and prints it, and the wrapper's
# number is read as the total rather than as the answer. Two clocks that
# disagree are not a contradiction. The gap between them IS the setup cost,
# and it is more often the larger one than anybody expects.
#
# THE A11Y OUTLINE DESCRIBES THE HYDRATED DOM (convicted 2026-09-21). Four
# probes in a row failed at one question -- what is the querystring parameter
# behind the Has SW filter -- because the claim being tested came from an
# accessibility semantic outline, and that outline is generated from the page
# AFTER JavaScript runs. `source.html` is what the server sent. They are not
# the same document. A <select> seen in the a11y outline is not evidence of a
# <select> in source.html, and grepping source.html for it will return 0
# forever, which reads as "the thing does not exist" when it means "you are
# reading the wrong file."
#
# THE RULE: name the capture file every DOM claim came from. If the claim came
# from accessibility_tree_summary.txt or from a screenshot, the probe that
# tests it must run against hydrated_dom.html, never source.html.
#
# AMENDED THE SAME DAY, by running that very probe. hydrated_dom.html carried
# NO filter select either: one named <select> (action) and four <input>s, in a
# page whose a11y outline lists [option] "Has SW". So the outline was never
# describing a hydrated <select>. IT WAS DESCRIBING AN ARIA ROLE. A
# <div role="option"> reports as [option] in an accessibility tree while
# carrying no name attribute and no form semantics at all.
# AN ACCESSIBILITY TREE NAMES ROLES, NOT TAGS. [option], [combobox] and
# [button] in an outline are claims about what a screen reader announces,
# never about what element exists or what it would submit. To learn a form
# control's name, read the markup. To learn whether a control is even a form
# control, read the markup FIRST.
#
# THE HALT BANNER (banked 2026-09-21, at the operator's instruction). Anything
# the human must DO that is not one of the five cars will be missed. Not might
# be. Will be. The five cars are myelinated; everything else is invisible.
# Prose does not work. A polite closing sentence does not work. Asking three
# times does not work, and that is the exact failure this bans: three turns in
# a row ending with "say the word and I will write those four facts", each one
# unread, because each one was a sentence.
# THE RULE, in two halves:
#   1. IF IT IS NOT A CAR, DO NOT ASK. Turn the ask into a car, or into a
#      paste-ready artifact the human can move without deciding anything, or
#      just do it yourself if you have the hands.
#   2. IF IT TRULY CANNOT BE A CAR, it gets a full-width ASCII HALT banner at
#      the TOP of the reply. Plain speech. Imperative. One action per line.
#      Peanut butter sandwich rules: "open the jar" beats "ensure the vessel
#      is accessible". No Claude-speak inside the banner. No explanation
#      inside the banner. The explanation goes after it, where skipping it
#      costs nothing.
#
# THE FINDING DORY RULE (banked 2026-09-24, cartridge foo-75b9c41a-94.zip, at
# the operator's instruction). The rules above already said "one action per
# line" and "never make the human infer the command from prose." Both were in
# context. The same ride still produced four failures on hand steps:
#   1. A HALT banner rode inside a code fence. The copy button took all of it
#      and bash ran the English ("FINISH: command not found").
#   2. `read -rs JIRA_TOKEN && export JIRA_TOKEN`, described as "waits quietly
#      for you to paste the token." No visible prompt, and "paste" had two
#      readings. The operator pasted the token INTO the command, then Ctrl+C.
#   3. The fix, `export JIRA_TOKEN="$(pbpaste)"`. The copy button is how every
#      command reaches the terminal, so at Enter the clipboard holds the
#      COMMAND, not the token. It worked only because the operator pasted,
#      held off on Enter, went and copied the token, came back, and pressed
#      Enter: a CAPTCHA nobody wrote down.
#   4. A patch anchored on a line that exists only if an earlier car, never
#      applied, had landed. This file refused it.
# Adjectives do not survive a model under load. This is a procedure. Run it on
# every step the human does by hand, before emitting it:
#   (a) READ IT AS DORY. The reader has no memory of the last line, is in a
#       hurry, takes every ambiguous word the wrong way, and acts on the first
#       thing that looks like an instruction. Walk the step from their chair:
#       which window is open, what is in the clipboard, what is on the screen.
#       Every way it can go wrong gets a sentence, or the step is redesigned.
#   (b) THE CLIPBOARD IS ALREADY IN USE. The command travels through it, so a
#       command never reads its input from the clipboard. A value only the
#       human has (a token, a path) is asked for at a VISIBLE, LABELED prompt,
#       and copying that value is its own numbered step AFTER the command is
#       running. Bash form:
#         read -rsp 'Paste your Jira token, then press Enter: ' JIRA_TOKEN; echo; export JIRA_TOKEN
#       Hidden input says so: "nothing appears when you paste; that is normal."
#       A placeholder is the other honest form, if the step names exactly
#       which characters to replace.
#   (c) EVERY STEP IS THREE PARTS: "Copy the block below, paste it into <which
#       window>, press Enter." Then the fence. Then "You will see: <exact
#       text>." A secret is checked by its length (echo ${#VAR}), never by
#       its value.
#   (d) EVERY FENCE IS WHAT ITS PASTE TARGET EXPECTS. A bash fence holds only
#       lines safe to run as-is; a banner or explanation is never fenced. A
#       fence with a Target line is a patch. A Car 2 fence is adhoc.txt lines.
#   (e) A HALT CARRIES ONE ACTION. A hand step that needs more than one action
#       is not a HALT: it becomes the whole turn. Its test is Car 1, other work
#       waits, and the next compile reads the receipt. One thing done so a
#       tired person cannot get it wrong beats five things done fast.
#   (f) A PATCH ANCHORS ON THIS COMPILE'S RAW SOURCE. Never on a line another
#       car would create; never "apply that one first."
#   (g) THE OPERATOR IS TOLD WHAT TO DO, NEVER WHAT TO CHECK (banked
#       2026-09-24, cartridge foo-dcfa8505-95.zip; convicted in the very
#       reply that proposed this rule). Car 1 ended with six numbered
#       forecasts of its own output and "If you see 0 here, stop": a branch
#       handed to the human, which THE HUMAN IS NOT THE BRANCH PREDICATE
#       already bans, and a list the operator read as six things to figure
#       out. The branch bought nothing: the same probe rode Car 2, so the
#       next compile would have read the 0 anyway.
#       THE RULE: Car 1 carries one instruction -- copy, paste into <which
#       window>, press Enter -- and nothing about what comes back. Forecasts
#       ride in Car 4, where the next model checks them against the
#       receipts. A guard the operator must not miss goes INSIDE the
#       command, so the shell or the program prints the verdict:
#         test -n "$JIRA_TOKEN" || echo "JIRA_TOKEN IS EMPTY IN THIS WINDOW"
#       The "You will see" in (c) is for a hand step whose output is fixed
#       and known (a prompt's label, "nothing appears"), never for a probe.
# THE TEST: a red team is fuzzing these instructions on a real operator in a
# high-reliability shop. Every misreading they find is your defect.
#
# THE DIVIDER IS NOT OPTIONAL (convicted 2026-09-22, six refusals in a row and
# a hand repair in vim). The emitter wrote the search marker, the old text,
# the REPLACE marker where the divider belongs, the new text, and then a
# closing slash-replace marker that does not exist in this grammar, all
# inside a four-backtick fence. This file said "No blocks found" six times,
# correctly, and the operator opened vim.
# THE GRAMMAR, in words so this comment can never parse as a block:
#   1. a Target line, INSIDE the fence, directly above the search marker
#   2. the search marker, then the exact old text
#   3. the divider marker, then the new text
#   4. the replace marker, and the block ENDS. There is no closing marker.
# The fence is exactly three backticks plus a word. The fence stripper
# matches three backticks and an optional word, so a four-backtick fence
# line survives into the body.
# WHY IT KEEPS HAPPENING: most patch dialects close their blocks, and a
# model under load reaches for the shape it has seen most often.
# COUNT THE MARKERS BEFORE EMITTING: three, in that order, once each.
# PROTOCOL MARKER AIRLOCK — the guard the 2026-07-26 player-piano.js incident
# called for. apply.py speaks a grammar of bare delimiters: [[[SEARCH]]],
# [[[DIVIDER]]], [[[REPLACE]]], [[[WRITE_FILE]]], [[[END_WRITE_FILE]]] (with 3-5
# bracket tolerance and {{{ }}} variants, mirroring the parser regexes below).
# When a malformed edit leaks one of those delimiters into a target file, the
# file is corrupted in the parser's own language and nothing downstream shouts.
# This regex is deliberately LINE-ANCHORED to a *bare* delimiter — a line that is
# nothing but the marker — because that is what debris looks like and what real
# source never is. apply.py, prompt.md, and prompt_foo.py mention the markers
# inline, backticked, or inside regex source, so this guard never blocks the
# tool from editing itself; the allowlist is belt-and-suspenders for docs that
# legitimately show a bare marker inside a fenced example.
_RESIDUAL_MARKER_RE = re.compile(
    r'^[ \t]*[\[{]{3,5}(?:SEARCH|DIVIDER|REPLACE|WRITE_FILE|END_WRITE_FILE)[\]}]{3,5}[ \t]*$'
)

# Basenames permitted to carry bare markers (they define or document the grammar).
PROTOCOL_GRAMMAR_FILES = frozenset({
    'apply.py', 'prompt.md', 'prompt_foo.py', 'AGENTS.md', 'README.md',
})
# AUTOLINK CONTAMINATION AIRLOCK (banked 2026-07-31, render-gap conviction).
# WITNESSED 2026-08-21 (tests/test_apply_airlock.py, 7/7 pass): surgical arm
# (positive + negative), WRITE_FILE arm (positive + creation-refusal +
# overwrite-refusal), both regex alternatives, and .md exemption all green.
# A chat renderer between the compiler and the model wraps BARE www-prefixed
# hosts in markdown link syntax. The model quotes the rendered form into a
# REPLACE block, and this tool -- being a faithful actuator -- writes the
# contamination into the file for real. The exact-match interlock catches
# contaminated READS (the SEARCH stops matching, which is exactly what
# happened to configuration.nix); nothing caught contaminated WRITES.
#
# THE SIGNATURE IS SELF-REFERENTIAL, and that is what makes it safe to enforce:
# the link TEXT equals the link TARGET minus its scheme. That is what
# autolinking produces and what a human essentially never types on purpose, so
# this cannot become the kind of always-firing guard that gets deleted. Same
# design philosophy as SECRET_TRIPWIRES: demand the exact shape, not the topic.
# .md targets are exempt -- a markdown document may legitimately carry one.
_AUTOLINK_CONTAMINATION_RE = re.compile(
    r'\[(www\.[^\]\s]+)\]\(https?://\1/?\)'
    r'|\[(https?://[^\]\s]+)\]\(\2/?\)'
)
def _autolink_contamination(text: str):
    """Return (lineno, line) for every self-referential markdown autolink."""
    return [(i, line) for i, line in enumerate(text.split('\n'), start=1)
            if _AUTOLINK_CONTAMINATION_RE.search(line)]

def _residual_marker_lines(text: str):
    """Return (lineno, line) for every bare protocol delimiter left in text."""
    return [(i, line) for i, line in enumerate(text.split('\n'), start=1)
            if _RESIDUAL_MARKER_RE.match(line)]

# BLANK-LINE GAP FINDER (convicted 2026-09-05, two blocks in one train, and
# the cause re-attributed the same day). EMPTY lines vanish between the
# compiler and the model while whitespace-only lines survive. The compiler is
# ACQUITTED by receipt: prompt_foo.py reads bodies raw, joins sections with
# double newlines, and carries no newline-run collapse (an rg for one read
# nothing), so the loss is in TRANSPORT, the paste into a chat window, the
# same class the render canary exists to catch. A model copying what it is
# told is raw source therefore cannot tell an absent blank from a hidden one,
# THE DISCRIMINATION QUESTION failing inside the payload itself. A SEARCH that
# spans a hidden blank fails the exact-match interlock, and the nearest-window
# scorer below then points rows off, because it rewards the longest SHIFTED
# run rather than the cause. This helper re-runs the search with every blank
# dropped from both sides and returns the file spans that match. It NEVER
# writes: the interlock stays exact, and the caller only prints the span so
# the repair is a paste. Nothing in the compiler can restore what the
# transport drops; the cure is on the model's side (anchor on single lines or
# blank-free spans, per checklist item 6) and on this side (the receipt).
# ZERO-SPAN SILENCE, DISCHARGED (convicted 2026-09-05, landed 2026-09-06).
# When this helper found ZERO spans the branch printed nothing, and the
# nearest-window report below showed only the block's FIRST line -- which, in
# the refusal that convicted it, MATCHED. A block differing by one character
# on line 13 therefore produced a receipt naming no line at all, and the
# repair happened by hand in vim. The FIRST DIVERGENCE block further down now
# walks the aligned pair forward and names the first differing line with both
# sides repr'd. Witnessed by straddle: a four-line SEARCH differing only on
# line 3, run against a throwaway file before and after, named nothing before
# and named line 3 after, with the file unchanged in both worlds.
def _blank_gap_spans(content: str, search_block: str):
    """0-based inclusive (start, end) spans of content matching search_block
    once every empty or whitespace-only line is dropped from both sides."""
    search_lines = [line for line in search_block.split('\n') if line.strip()]
    if not search_lines:
        return []
    kept = [(i, line) for i, line in enumerate(content.split('\n')) if line.strip()]
    width = len(search_lines)
    spans = []
    for k in range(len(kept) - width + 1):
        if all(kept[k + j][1] == search_lines[j] for j in range(width)):
            spans.append((kept[k][0], kept[k + width - 1][0]))
    return spans

def apply_search_replace_patch(payload: str) -> bool:
    # 1. NORMALIZE PAYLOAD WHITESPACE
    # Convert non-breaking spaces to regular spaces and normalize line endings
    payload = payload.replace('\xa0', ' ').replace('\r\n', '\n')

    # WHOLE-FILE WRITE ESCAPE HATCH (captured BEFORE fence-stripping)
    # A Target line immediately followed by [[[WRITE_FILE]]] ... [[[END_WRITE_FILE]]]
    # replaces (or creates) the entire file verbatim, with no SEARCH block to
    # reproduce. Extracted here, ahead of the fence-strip below, so files that
    # legitimately contain their own code fences (markdown, docs) survive untouched.
    # The Target line is REQUIRED: with no surrounding context to anchor on, the
    # filename is the only safeguard against writing into the void.
    write_file_pattern = re.compile(
        r'(?:File|Target):\s*`?([^`\s*]+)`?\s*\n[\[{]{3,5}WRITE_FILE[\]}]{3,5}\n(.*?)\n[\[{]{3,5}END_WRITE_FILE[\]}]{3,5}',
        re.DOTALL | re.IGNORECASE
    )
    write_matches = write_file_pattern.findall(payload)

    # Excise the WRITE_FILE regions before the surgical scan below. A whole-file
    # body can legitimately contain a complete SEARCH/DIVIDER/REPLACE triple —
    # most likely when rewriting the protocol files themselves — and without this
    # the same payload would fire once as a write and again as a surgical patch.
    payload = write_file_pattern.sub('', payload)

    # Strip markdown code fences to bypass web UI whitespace destruction
    # (This successfully prevents the chat framework from eating our left-indentation!)
    payload = re.sub(r'^```[a-zA-Z0-9]*\s*$', '', payload, flags=re.MULTILINE)

    # Regex to find an optional 'File:' indicator followed by SEARCH/DIVIDER/REPLACE blocks
    # A more robust regex that ignores bracket width variations and code fence lines
    block_pattern = re.compile(
        r'(?:(?:File|Target):\s*`?([^`\s*]+)`?\s*\n)?[\[{]{3,5}SEARCH[\]}]{3,5}\n(.*?)\n[\[{]{3,5}DIVIDER[\]}]{3,5}\n(.*?)\n[\[{]{3,5}REPLACE[\]}]{3,5}',
        re.DOTALL | re.IGNORECASE
    )

    matches = block_pattern.findall(payload)

    if not matches and not write_matches:
        print("❌ Error: No [[[SEARCH]]]/[[[REPLACE]]] or [[[WRITE_FILE]]] blocks found in payload.")
        return False

    success = True

    # Process wholesale writes first so a single payload can create one file and
    # then surgically patch another in the same turn.
    for filename_match, file_content in write_matches:
        filename = os.path.expanduser(filename_match.strip('` \t\n'))
        if not filename:
            print("❌ Error: Missing target filename before the WRITE_FILE block.")
            success = False
            continue

        file_content = file_content.replace('\xa0', ' ').replace('\r\n', '\n')
        # POSIX courtesy: guarantee exactly one trailing newline.
        file_content = file_content.rstrip('\n') + '\n'

        # PROTOCOL MARKER AIRLOCK (whole-file arm) — refuse to write our own grammar.
        if os.path.basename(filename) not in PROTOCOL_GRAMMAR_FILES:
            residue = _residual_marker_lines(file_content)
            if residue:
                print(f"❌ Error: Whole-file write of '{filename}' aborted. "
                      f"Residual patch-protocol marker(s) in the body:")
                for lineno, line in residue:
                    print(f"    >>> {lineno:4d}: {line!r}")
                success = False
                continue

        # AUTOLINK CONTAMINATION AIRLOCK (whole-file arm)
        if not filename.endswith('.md'):
            autolinks = _autolink_contamination(file_content)
            if autolinks:
                print(f"❌ Error: Whole-file write of '{filename}' aborted. "
                      f"Self-referential markdown autolink(s) in the body:")
                for lineno, line in autolinks:
                    print(f"    >>> {lineno:4d}: {line.strip()!r}")
                print("    RENDER-GAP signature. The FILE is probably correct and the")
                print("    PAYLOAD was not. Re-read from a second channel; nothing written.")
                success = False
                continue
        # JSON SYNTAX AIRLOCK (whole-file arm)
        if filename.endswith('.json'):
            import json
            try:
                json.loads(file_content)
            except json.JSONDecodeError as e:
                print(f"❌ Error: Whole-file write of '{filename}' aborted. Invalid JSON:\n   {e}")
                success = False
                continue

        # AST VALIDATION AIRLOCK (same safeguard the surgical path enforces)
        if filename.endswith('.py'):
            import ast
            try:
                ast.parse(file_content)
            except SyntaxError as e:
                print(f"❌ Error: Whole-file write of '{filename}' aborted. Invalid Python syntax:\n   {e}")
                success = False
                continue

        existed = os.path.exists(filename)
        parent = os.path.dirname(filename)
        if parent:
            os.makedirs(parent, exist_ok=True)
        with open(filename, 'w', encoding='utf-8') as f:
            f.write(file_content)

        verb = "OVERWROTE" if existed else "CREATED"
        print(f"✅ WHOLE-FILE WRITE: {verb} '{filename}'.")

    for filename_match, search_block, replace_block in matches:
        filename = os.path.expanduser(filename_match.strip('` \t\n')) if filename_match else None
        
        if not filename:
            print("❌ Error: Missing target filename before the SEARCH block.")
            # DIAGNOSTIC: Show context around this SEARCH block in the raw payload
            # Find the position of the search block content in the payload
            search_snippet = search_block[:80].split('\n')[0]
            # Find surrounding lines in payload
            payload_lines = payload.split('\n')
            for li, pl in enumerate(payload_lines):
                if search_snippet and search_snippet.strip() in pl:
                    ctx_start = max(0, li - 4)
                    ctx_end = min(len(payload_lines), li + 3)
                    print(f"\n--- DIAGNOSTIC: Payload context around SEARCH block ---")
                    print(f"  The [[[SEARCH]]] block was found but no 'Target: `filename`' line")
                    print(f"  immediately preceded it. Here is what WAS there:")
                    for ci, cl in enumerate(payload_lines[ctx_start:ctx_end], start=ctx_start+1):
                        print(f"  {ci:4d}: {repr(cl)}")
                    print(f"\n  FIX: Add 'Target: `path/to/file`' on the line")
                    print(f"  immediately before the [[[SEARCH]]] marker, no blank lines between.")
                    print(f"--- END DIAGNOSTIC ---\n")
                    break
            success = False
            continue

        if not os.path.exists(filename):
            print(f"❌ Error: Target file '{filename}' not found.")
            success = False
            continue

        with open(filename, 'r', encoding='utf-8') as f:
            content = f.read()

        # 2. NORMALIZE TARGET FILE WHITESPACE
        content = content.replace('\xa0', ' ').replace('\r\n', '\n')
        search_block = search_block.replace('\xa0', ' ').replace('\r\n', '\n')
        replace_block = replace_block.replace('\xa0', ' ').replace('\r\n', '\n')

        # The Exact Match Invariant
        # A SUBSTRING COUNT, NOT A LINE MATCH, and that is worth naming here
        # because it is a technique (witnessed 2026-09-10, ten of ten blocks
        # landed in one car). The block regex takes everything between the
        # SEARCH marker's newline and the DIVIDER's, so a SEARCH may begin and
        # end MID-LINE. When a target line carries alignment padding a model
        # cannot count through transport -- a docstring's column of trailing
        # comments, a README's padded roster -- anchor on the unpadded TAIL
        # and the file's own padding survives untouched. The interlock is
        # exactly as strict either way, one occurrence or refusal; what shrinks
        # is the number of bytes the model must reproduce, and fewer bytes is
        # fewer ways to be wrong. THE COST: the refusal diagnostics below think
        # in lines, so a mid-line anchor that misses gets a poorer receipt.
        # Prefer whole lines wherever the padding CAN be counted.
        # THE TAIL-APPEND (witnessed 2026-09-10, the wallet ride: 20 of 20
        # blocks landed across five cars, nine of them mid-line). To insert
        # a NEW line directly after a padded line, SEARCH that line's unpadded
        # tail and REPLACE with the tail, a newline, and the new line: the
        # padded line is continued, never reproduced, and the new line's
        # padding is the model's own to choose. The same trick steps past an
        # em dash -- anchor on the text AFTER the dash and the dash is never
        # typed -- so the two-hyphen misspelling EMPTY-REPLACE below convicted
        # is refused at the keyboard instead of at the interlock.
        # WITNESSED AGAIN 2026-09-10, the botify ride: 39 of 39 blocks landed
        # across nine cars, most anchored mid-line on docstring tails, a
        # padded README row, and a help string -- zero refusals, zero hand
        # repairs, one docstring car closing the ride as a null straddle.
        match_count = content.count(search_block)
        
        if match_count == 0:
            # EMPTY-REPLACE DELETION (witnessed 2026-08-30, seven of eight): a
            # deletion block's REPLACE is the empty string, and str.count('')
            # returns len(content)+1, so an exact-match miss printed
            # "replacement is ambiguous (found 296014 times)" -- the file's
            # character count wearing a match count's label -- and skipped the
            # nearest-line diagnostic below, which would have shown the em dash
            # the SEARCH had spelled as two hyphens. Route it to not-found.
            # THE SUBSET REPLACE (convicted 2026-09-04, dedupe car): when the
            # REPLACE block is a SUBSTRING of the SEARCH block -- every dedupe
            # car, by construction -- it is present in the file BEFORE the
            # patch, so this heuristic read "ambiguous (found 2 times)" for a
            # plain not-found and skipped the nearest-line diagnostic that
            # would have shown the invisible blank. A subset REPLACE can never
            # mean "already applied"; fall through to the real diagnostic.
            already_applied_count = (content.count(replace_block)
                                     if replace_block and replace_block not in search_block
                                     else 0)
            if already_applied_count == 1:
                print(f"✅ PATCH ALREADY APPLIED: '{filename}' already contains the replacement block.")
                continue
            if already_applied_count > 1:
                print(f"❌ Warning: SEARCH block missing but replacement is ambiguous (found {already_applied_count} times) in '{filename}'. Skipping.")
                success = False
                continue

            print(f"❌ Warning: SEARCH block not found in '{filename}'. Skipping.")
            # BLANK-LINE GAP: the block may match exactly EXCEPT for empty lines
            # the payload never showed. Say so and print the file's own lines
            # for that span, so the repair is a paste. Diagnostic only.
            gap_spans = _blank_gap_spans(content, search_block)
            if len(gap_spans) == 1:
                gap_start, gap_end = gap_spans[0]
                gap_lines = content.split('\n')[gap_start:gap_end + 1]
                gap_blanks = sum(1 for line in gap_lines if not line.strip())
                print(f"\n--- BLANK-LINE GAP: the block matches lines {gap_start + 1}-{gap_end + 1} "
                      f"except for {gap_blanks} blank line(s) the payload did not show ---")
                for i, line in enumerate(gap_lines, start=gap_start + 1):
                    print(f"  {i:4d}: {line!r}")
                print("  Re-emit the SEARCH block as exactly these lines, blanks included.")
                print("--- END BLANK-LINE GAP ---\n")
            elif len(gap_spans) > 1:
                print(f"\n--- BLANK-LINE GAP: {len(gap_spans)} blank-insensitive matches; "
                      "not unique even ignoring blank lines ---\n")
            # DIAGNOSTIC: Find closest matching window in target file
            search_lines = search_block.split('\n')
            content_lines = content.split('\n')
            search_len = len(search_lines)
            best_score, best_idx = 0, 0
            for i in range(max(0, len(content_lines) - search_len + 1)):
                score = sum(1 for j in range(min(search_len, len(content_lines) - i))
                            if content_lines[i+j].lstrip() == search_lines[j].lstrip())
                if score > best_score:
                    best_score, best_idx = score, i
            print(f"\n--- DIAGNOSTIC: First line of your SEARCH block ---")
            print(f"  SEARCH repr : {repr(search_lines[0])}")
            file_first = content_lines[best_idx] if best_idx < len(content_lines) else ''
            print(f"  FILE nearest: {repr(file_first)}")
            search_indent = len(search_lines[0]) - len(search_lines[0].lstrip())
            file_indent = len(file_first) - len(file_first.lstrip())
            if search_indent != file_indent:
                print(f"  ⚠ Indentation mismatch: SEARCH has {search_indent} spaces, file has {file_indent} spaces.")
                corrected = (' ' * file_indent) + search_lines[0].lstrip()
                print(f"  ✓ Corrected first line should be: {repr(corrected)}")
            if search_lines[0].lstrip() != file_first.lstrip():
                print(f"  ⚠ Content mismatch even after stripping: lines differ beyond whitespace.")
            # FIRST DIVERGENCE (TODO of 2026-09-05, discharged 2026-09-06). The
            # blank-gap finder above prints a span only when it finds exactly
            # one; on ZERO spans it printed NOTHING, and the nearest-window
            # report below shows only the block's FIRST line -- which, in the
            # refusal that convicted this, MATCHED. So a block differing by one
            # character on line 13 produced a receipt naming no divergent line
            # at all, and the repair happened by hand in vim. This walks the
            # aligned pair forward and names the first line that actually
            # differs, both sides repr'd, so the operator can see the byte.
            # ONLY ON ZERO SPANS: a real blank-line gap already has a better
            # receipt directly above, and printing both would make the reader
            # choose between two diagnoses of one refusal.
            # LSTRIP-EQUAL COUNTS AS MATCHING, mirroring the scorer that chose
            # this window, so what gets named is a CONTENT difference; pure
            # indentation drift is already reported two lines up and does not
            # need a second, differently-worded witness.
            # THE NO-DIVERGENCE CASE IS SAID OUT LOUD. When every aligned line
            # matches -- the SEARCH is a strict prefix of the window, or runs
            # off the end of the file -- silence would read exactly like the
            # zero-span silence this block exists to end.
            if not gap_spans:
                divergence = None
                for j in range(search_len):
                    file_idx = best_idx + j
                    if file_idx >= len(content_lines):
                        divergence = (j, None)
                        break
                    if content_lines[file_idx].lstrip() != search_lines[j].lstrip():
                        divergence = (j, file_idx)
                        break
                print("\n--- FIRST DIVERGENCE (no blank-insensitive match; this is not a blank-line gap) ---")
                if divergence is None:
                    print("  Every aligned line matches; the SEARCH block is a prefix of the")
                    print("  nearest window, or the window runs past the end of the file.")
                    print("  Extend or shorten the block so it names a unique region.")
                elif divergence[1] is None:
                    print(f"  SEARCH line {divergence[0] + 1} has no counterpart: the block runs")
                    print(f"  past the end of {filename} from the nearest window.")
                else:
                    j, file_idx = divergence
                    print(f"  SEARCH line {j + 1}   : {search_lines[j]!r}")
                    print(f"  FILE line {file_idx + 1}     : {content_lines[file_idx]!r}")
                print("--- END FIRST DIVERGENCE ---")
            # Also show the full SEARCH block so the LLM can compare against the source
            print(f"--- YOUR SUBMITTED SEARCH BLOCK (verbatim) ---")
            for li, sl in enumerate(search_lines, start=1):
                print(f"  {li:3d}: {repr(sl)}")
            print(f"--- END SUBMITTED SEARCH BLOCK ---\n")
            success = False
            continue
        elif match_count > 1:
            print(f"❌ Warning: Ambiguous match (found {match_count} times) in '{filename}'. Skipping.")
            success = False
            continue
            
        # IDEMPOTENT INSERTION (convicted 2026-09-11: `app` ran twice on one
        # patch file). The already-applied guard above runs only on a MISS,
        # and an insertion never misses: its SEARCH is a subset of its own
        # REPLACE, so the anchor is still present after it lands and a second
        # run inserts a second copy. Nine plain replacements were caught that
        # day; the three insertions -- a tail-append, a paragraph before an
        # anchor, a function before an anchor -- each landed twice and were
        # committed before anyone read the diff. When SEARCH occurs once and
        # the file already holds REPLACE verbatim, that occurrence sits inside
        # the landed insertion: say so, and touch nothing.
        # WITNESSED 2026-09-11 on the NEGATIVE path: the wallet.py UNCHANGED
        # car carried two insertions through this guard on a fresh file and
        # both landed exactly once. The positive path -- a second `app` on
        # the same patch file printing ALREADY APPLIED for an insertion -- is
        # still unwitnessed; a throwaway-file straddle would close it.
        if (search_block in replace_block and replace_block != search_block
                and content.count(replace_block) >= 1):
            print(f"✅ PATCH ALREADY APPLIED: '{filename}' already contains the inserted block.")
            continue

        # The Surgical Strike
        new_content = content.replace(search_block, replace_block, 1)

        # PROTOCOL MARKER AIRLOCK (surgical arm, first of the airlocks) — refuse
        # to write a file that still carries a bare protocol delimiter. Runs
        # ahead of the JSON/Nix/AST validators because a leaked marker also trips
        # those, but with a symptom message that points nowhere near the cause.
        if os.path.basename(filename) not in PROTOCOL_GRAMMAR_FILES:
            residue = _residual_marker_lines(new_content)
            if residue:
                print(f"❌ Error: Patching '{filename}' aborted. "
                      f"Residual patch-protocol marker(s) survived substitution:")
                for lineno, line in residue:
                    print(f"    >>> {lineno:4d}: {line!r}")
                print("    A bare [[[SEARCH]]]/[[[DIVIDER]]]/[[[REPLACE]]]/[[[WRITE_FILE]]] "
                      "line in the OUTPUT means the edit leaked the tool's own grammar "
                      "into the file. Fix the block boundaries and re-run; nothing was written.")
                success = False
                continue
        
        # AUTOLINK CONTAMINATION AIRLOCK (surgical arm). Checked against the
        # REPLACE block ALONE, never new_content: an edit must not be blamed
        # for debris that was already in the file, and a file already carrying
        # contamination still needs to be editable in order to be repaired.
        if not filename.endswith('.md'):
            autolinks = _autolink_contamination(replace_block)
            if autolinks:
                print(f"❌ Error: Patching '{filename}' aborted. "
                      f"REPLACE block carries self-referential markdown autolink(s):")
                for lineno, line in autolinks:
                    print(f"    >>> replace:{lineno}: {line.strip()!r}")
                print("    RENDER-GAP signature: a bare www-host that a chat renderer")
                print("    linkified between the compiler and the model. The FILE is")
                print("    almost certainly correct; the PAYLOAD was not. Confirm the")
                print("    region against a second channel (git diff, a fresh compile)")
                print("    before re-emitting. Nothing was written.")
                success = False
                continue
        # JSON SYNTAX AIRLOCK (third of three). .py gets AST, .nix gets
        # nix-instantiate, and .json got NOTHING until scenario patches
        # started landing into it -- a format where a misplaced comma
        # produces a file that still reads as text, writes without complaint,
        # and dies silently in the browser's fetch(). Conviction: the
        # 2026-07-26 introduction.json edits were proven clean only by a
        # hand-run json.load echoed as a probe, because this branch did not
        # exist. JSONDecodeError carries lineno/colno, so the refusal names
        # the exact character that broke.
        if filename.endswith('.json'):
            import json
            try:
                json.loads(new_content)
            except json.JSONDecodeError as e:
                print(f"❌ Error: Patching '{filename}' aborted. Invalid JSON:\n   {e}")
                err_lines = new_content.split('\n')
                start = max(0, e.lineno - 3)
                end = min(len(err_lines), e.lineno + 2)
                print("--- DIAGNOSTIC: Context around JSON error ---")
                for i, ln in enumerate(err_lines[start:end], start=start + 1):
                    marker = " >>>" if i == e.lineno else "    "
                    print(f"{marker} {i:4d}: {ln}")
                print("--- END DIAGNOSTIC ---")
                success = False
                continue

        # NIX SYNTAX AIRLOCK
        if filename.endswith('.nix'):
            import tempfile
            with tempfile.NamedTemporaryFile(mode='w', suffix='.nix', delete=False) as tmp:
                tmp.write(new_content)
                tmp_path = tmp.name
            nix_check = subprocess.run(
                ['nix-instantiate', '--parse', tmp_path],
                capture_output=True, text=True,
                env={**os.environ, 'LD_LIBRARY_PATH': ''}
            )
            os.unlink(tmp_path)
            if nix_check.returncode != 0:
                print(f"❌ Error: Patching '{filename}' aborted. Invalid Nix syntax:\n   {nix_check.stderr.strip()}")
                success = False
                continue

        # AST VALIDATION AIRLOCK (The Final Safeguard)
        if filename.endswith('.py'):
            import ast
            try:
                ast.parse(new_content)
            except SyntaxError as e:
                print(f"❌ Error: Patching '{filename}' aborted. Invalid Python syntax:\n   {e}")
                err_lines = new_content.split('\n')
                err_lineno = e.lineno or 0
                start = max(0, err_lineno - 3)
                end = min(len(err_lines), err_lineno + 2)
                print("--- DIAGNOSTIC: Context around syntax error ---")
                for i, ln in enumerate(err_lines[start:end], start=start+1):
                    marker = " >>>" if i == err_lineno else "    "
                    print(f"{marker} {i:4d}: {ln}")
                print("--- END DIAGNOSTIC ---")
                success = False
                continue

        with open(filename, 'w', encoding='utf-8') as f:
            f.write(new_content)
            
        print(f"✅ DETERMINISTIC PATCH APPLIED: Successfully mutated '{filename}'.")
        
    return success

def main():
    # Read the raw Markdown payload from the Unix pipe
    payload = sys.stdin.read()
    success = apply_search_replace_patch(payload)
    sys.exit(0 if success else 1)

if __name__ == "__main__":
    main()
